name: jaguar_reflect
description: Reflection based alternative for Jaguar
version: 2.0.0-dev
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: http://jaguar-dart.github.io

environment:
  sdk: ">=2.0.0-dev.35.0 <2.0.0"

dependencies:
  jaguar: ^2.0.0-dev
  dice: ^1.7.0

##### TODO: REMOVE BEFORE PUBLISHING #####
dependency_overrides:
  jaguar:
    path: ../jaguar
##########################################

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
