name: jaguar_generator
description: Generator for Jaguar
version: 1.3.1
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: http://jaguar-dart.github.io

environment:
  sdk: ">=1.8.0 <3.0.0"

dependencies:
  build_runner: ^0.7.0
  source_gen: ^0.7.3
  build: ^0.11.2
  jaguar: ^1.3.4
  analyzer: ^0.30.0

dev_dependencies:
  test:

dependency_overrides:
  jaguar:
    path: ../jaguar

executables:
  jaguar_gen:
