builders:
  jaguar_generator:
    import: "package:jaguar_generator/builder.dart"
    builder_factories: ["jaguarBuilder"]
    build_extensions: {".dart": [".jroutes.dart"]}
    auto_apply: root_package
    build_to: source