name: jaguar_generator
description: Generator for Jaguar
version: 2.4.4
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: http://jaguar-dart.github.io

documentation:

environment:
  sdk: ">=2.0.0-dev.65 <3.0.0"

dependencies:
  analyzer: ^0.33.0
  build: ^1.0.0
  logging: ^0.11.0
  source_gen: ^0.9.0
  meta: ^1.1.5
  jaguar: ^2.4.19

dev_dependencies:
  test: ^1.3.0
  build_runner: ^1.0.0
  collection: ^1.14.10
  path: ^1.6.2
