name: jaguar
version: 0.0.3
description: jaguar is a performant server side framework
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: http://jaguar-dart.github.io

executables:
  jaguar:

dependencies:
  http_server: ">=0.9.6 <0.10.0"
  mime: ">=0.9.3 <0.10.0"
  logging:
  intl:
  cookies:
  jaguar_generator:
    path: ../jaguar_generator
    # git: https://github.com/Jaguar-dart/jaguar_generator.git

dev_dependencies:
  test: 0.12.15+10
