name: jaguar
version: 0.0.3
description: jaguar is a performant server side framework
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: http://jaguar-dart.github.io

executables:
  jaguar:

dependencies:
  source_gen: ">=0.5.1+3 <0.6.0"
  build: ">=0.4.1 <0.5.0"
  yaml: ">=2.1.10 <3.0.0"
  http_server: ">=0.9.6 <0.10.0"
  mime: ">=0.9.3 <0.10.0"
  logging:
  intl:
  cookies:
  source_gen_help:
    git: https://github.com/Jaguar-dart/source_gen_help.git

dev_dependencies:
  test: 0.12.15+10
