name: jaguar
version: 0.6.23
description: Jaguar is a production ready HTTP server framework built for speed, simplicity and extensiblity
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: http://jaguar-dart.github.io

documentation:

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  yaml: ^2.1.12
  args: ^1.2.0
  http_server: ">=0.9.6 <0.10.0"
  mime: ">=0.9.3 <0.10.0"
  logging: ">=0.11.3 <0.12.0"
  intl: ">=0.15.0 <0.16.0"
  stack_trace: '>=1.7.0 <2.0.0'
  quiver_hashcode: '>=1.0.0 <2.0.0'
  mustache: ">=0.2.5+1 <0.3.0"
  collection: ">=1.14.1 <2.0.0"
  dice: ^1.7.0
  crypto: ^2.0.2
  meta: ^1.1.2
  path: ^1.5.1

dev_dependencies:
  cookies:
  test: ^0.12.15+10
  http:
  jaguar_client: ^0.2.1