name: jaguar
version: 0.0.1
description: jaguar is a performant server side framework

author: Jaguar Authors
homepage: https://github.com/Jaguar-dart/jaguar

executables:
  jaguar:

dependencies:
  source_gen: 0.5.1+3
  build: 0.4.1
  yaml: 2.1.10
  http_server: 0.9.6
  mime: 0.9.3
