name: jaguar
version: 0.0.3
description: jaguar is a performant server side framework

author: Jaguar Authors <segaud.kevin@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar

executables:
  jaguar:

dependencies:
  source_gen: ">=0.5.1+3 <0.6.0"
  build: ">=0.4.1 <0.5.0"
  yaml: ">=2.1.10 <3.0.0"
  http_server: ">=0.9.6 <0.10.0"
  mime: ">=0.9.3 <0.10.0"

dev_dependencies:
  test: 0.12.15+10
