name: jaguar
version: 1.3.6
description: Jaguar is a production ready HTTP server framework built for speed, simplicity and extensiblity
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: http://jaguar-dart.github.io

documentation:

environment:
  sdk: ">=1.8.0 <3.0.0"

dependencies:
  args: ">=0.13.7 <1.3.0"
  http_server: ">=0.9.6 <0.10.0"
  mime: ">=0.9.3 <0.10.0"
  logging: ">=0.11.3 <0.12.0"
  stack_trace: '>=1.7.0 <2.0.0'
  meta: ">=1.0.2 <1.2.0"
  path: ">=0.9.0 <2.0.0"
  collection: ">=1.14.5 <2.0.0"
  crypto: ^2.0.2
  yaml: ^2.1.12

dev_dependencies:
  jaguar_reflect: ^1.3.2
  cookies:
  test: ^0.12.15+10
  http:
  jaguar_client: ^0.2.1
  dice: ^1.7.0
  jaguar_generator: ^1.3.1
  build_runner: ^0.7.0
  mongo_dart: