name: jaguar_auth
description: Authentication interceptors and helper functions for Jaguar
version: 2.1.2
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_auth

documentation:

environment:
  sdk: ">=2.0.0-dev.60.0 <3.0.0"

dependencies:
  jaguar: ^2.1.24
  jaguar_common: ^0.2.0
  crypto: ^2.0.3

dev_dependencies:
  test: ^1.2.0
  http: ^0.11.3
  jaguar_reflect: ^2.1.4
  jaguar_client: ^2.1.4
  jaguar_resty: ^2.5.10
  jaguar_example_session_models: ^2.1.1