name: jaguar_auth
description: Authentication interceptors and helper functions for Jaguar
version: 2.1.1
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_auth

documentation:

environment:
  sdk: '>=1.20.0 <2.0.0'

dependencies:
  jaguar: ^2.1.9
  jaguar_common: ^0.2.0
  crypto: ^2.0.3

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  http: ^0.11.3
  jaguar_reflect: ^2.1.1
  jaguar_client: ^2.1.4
  jaguar_resty: ^2.5.10

dependency_overrides:
  jaguar:
    path: ../jaguar
  jaguar_reflect:
    path: ../reflect