name: jaguar_settings
version: 4.0.1
description: Settings parser for Jaguar.
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: http://jaguar-dart.github.io

environment:
  sdk: '>2.0.0 <3.0.0'

dependencies:
  args: ^1.5.1
  yaml: ^2.1.15
  jaguar_serializer: ^2.2.8

dev_dependencies:
  test:
