name: jaguar_dev_proxy
description: Jaguar reverse proxy implementation for dev
version: 3.0.0
homepage: https://jaguar-dart.github.io/
repository: https://github.com/Jaguar-dart/jaguar

documentation:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  jaguar: ^3.0.6
  path: ^1.8.0

dev_dependencies:
  test: ^1.17.2
  build_runner: ^2.0.1
  build_web_compilers: ^3.0.0