name: jaguar_dev_proxy
description: Jaguar reverse proxy implementation for dev
version: 2.1.1
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_dev_proxy

documentation:

environment:
  sdk: '>=2.0.0-dev <2.0.0'

dependencies:
  jaguar: ^2.1.1
  path: '>=0.9.0 <2.0.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  build_runner: ^0.7.0
  build_web_compilers: ^0.2.0