name: jaguar_auth_mongo
description: Jaguar AuthModelManager for MongoDb backend
version: 1.3.1
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_auth_mongo

documentation:

environment:
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  jaguar: ^1.3.4
  jaguar_auth: ^1.3.1
  jaguar_common: ^0.2.2
  mongo_dart: ^0.3.0
  jaguar_serializer: ^0.5.1
  auth_header: ^0.0.3
  jaguar_mongo: ^1.3.1

dev_dependencies:
  test: ^0.12.0
  jaguar_serializer_mongo: ^0.2.0
  jaguar_reflect: ^1.3.2
