name: jaguar_auth_mongo
description: MongoDb backed UserFetcher for authentication and authorization. Use it with `jaguar_auth`.
version: 2.4.1
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: http://jaguar-dart.github.io

documentation:

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  jaguar: ^2.4.4
  jaguar_auth: ^2.4.1
  jaguar_common: ^2.1.1
  mongo_dart: ^0.3.3
  jaguar_serializer: ^2.2.0
  auth_header: ^2.1.1
  jaguar_mongo: ^2.4.1

dev_dependencies:
  test: ^1.3.0
  jaguar_serializer_mongo: ^2.1.1
  jaguar_reflect: ^2.4.0
  build_runner: ^0.10.0
  jaguar_serializer_cli: ^2.2.0
  jaguar_client: ^2.4.1
  jaguar_resty: ^2.8.0
  jaguar_example_session_models: ^2.1.6
