name: jaguar_auth_mongo
description: MongoDb backed UserFetcher for authentication and authorization. Use it with `jaguar_auth`.
version: 2.1.2
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar

documentation:

environment:
  sdk: ">=2.0.0-dev.60.0 <3.0.0"

dependencies:
  jaguar: ^2.1.15
  jaguar_auth: ^2.1.2
  jaguar_common: ^0.2.2
  mongo_dart: ^0.3.2
  jaguar_serializer: ^2.1.8
  auth_header: ^0.0.3
  jaguar_mongo: ^2.1.1

dev_dependencies:
  test: ^1.2.0
  jaguar_serializer_mongo: ^2.1.1
  jaguar_reflect: ^2.1.4
  build_runner: ^0.9.0
  jaguar_serializer_cli: ^2.1.24
