name: jaguar_auth_mongo
description: Jaguar authentication UserFetcher for MongoDb.
version: 2.1.1
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_auth_mongo

documentation:

environment:
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  jaguar: ^2.1.10
  jaguar_auth: ^2.1.1
  jaguar_common: ^0.2.2
  mongo_dart: ^0.3.2
  jaguar_serializer: ^2.1.8
  auth_header: ^0.0.3
  jaguar_mongo: ^2.1.1

dev_dependencies:
  test: ^0.12.0
  # jaguar_serializer_mongo: ^0.2.0
  jaguar_reflect: ^2.1.1
