name: jaguar_eventsource
description: Server side events plugin for Jaguar dart.
version: 1.0.0
homepage: https://jaguar-dart.github.io
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  jaguar: ^2.4.30
  pedantic: ^1.0.0

dev_dependencies:
  test: ^1.0.0