name: jaguar_redirecter
version: 2.2.0
description: Plugin to perform HTTP to HTTPS redirection or redirection to another server.
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
homepage: http://jaguar-dart.github.io

environment:
  sdk: ">=2.0.0-dev.65 <3.0.0"

dependencies:
  jaguar: ^2.2.4

dev_dependencies:
  test: ^1.3.0
