name: jaguar
version: 2.0.0-dev
description: Jaguar is a production ready HTTP server framework built for speed, simplicity and extensiblity
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: http://jaguar-dart.github.io

documentation:

environment:
  sdk: ">=2.0.0-dev.35.0 <2.0.0"

dependencies:
  args: ">=0.13.7 <2.0.0"
  http_server: ">=0.9.6 <0.10.0"
  mime: ">=0.9.3 <0.10.0"
  logging: ">=0.11.3 <0.12.0"
  stack_trace: '>=1.7.0 <2.0.0'
  meta: ">=1.0.2 <1.2.0"
  path: ">=0.9.0 <2.0.0"
  collection: ">=1.14.5 <2.0.0"
  crypto: ^2.0.2
  yaml: ^2.1.12

dev_dependencies:
  jaguar_reflect:
    path: ../jaguar_reflect
  jaguar_generator:
    path: ../jaguar_generator
  jaguar_resty: ^1.1.1
  cookies:
  test: ^0.12.15+10
  http:
  dice: ^1.7.0
  build_runner: ^0.8.0
  mongo_dart:
