name: jaguar
version: 2.1.37
description: Jaguar is a production ready HTTP server framework built for speed, simplicity and extensiblity
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: http://jaguar-dart.github.io

documentation:

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  http_server: ^0.9.7
  mime: ^0.9.6
  logging: ^0.11.3
  stack_trace: ^1.9.2
  path: ^1.6.1
  collection: ^1.14.10
  crypto: ^2.0.5
  auth_header: ^2.1.1
  jaguar_common: ^2.1.1

dev_dependencies:
  analyzer: ^0.32.0
  jaguar_reflect: ^2.1.4
  test: ^1.3.0
  jaguar_resty: ^2.6.2
  http:
  client_cookie:
  http_parser: