name: jaguar
version: 3.0.6
description: Jaguar is a production ready HTTP server framework built for speed, simplicity and extensiblity
homepage: https://jaguar-dart.github.io
repository: https://github.com/Jaguar-dart/jaguar

documentation:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http_server: ^1.0.0
  mime: ^1.0.0
  logging: ^1.0.1
  stack_trace: ^1.9.2
  path: ^1.6.1
  collection: ^1.14.6
  crypto: ^3.0.0
  auth_header: ^3.0.1
  jaguar_common: ^3.0.0
  path_tree: ^3.0.0
  # jaguar_serializer: ^2.2.8
  meta: ">1.1.0 <2.0.0"

dev_dependencies:
  # analyzer: ^0.32.0
  test: ^1.5.1
  jaguar_resty: ^3.0.0
  http: ^0.13.0
  client_cookie: ^3.0.2
  http_parser:
