name: jaguar
version: 2.1.10
description: Jaguar is a production ready HTTP server framework built for speed, simplicity and extensiblity
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: http://jaguar-dart.github.io

documentation:

environment:
  sdk: ">=2.0.0-dev.65.0 <3.0.0"

dependencies:
  http_server: ^0.9.7
  mime: ^0.9.6
  logging: ^0.11.3
  stack_trace: ^1.9.2
  meta: ^1.1.5
  path: ^1.6.1
  collection: ^1.14.10
  crypto: ^2.0.5
  auth_header: ^0.0.3

dev_dependencies:
  jaguar_reflect: ^2.1.2
  test: ^1.2.0
  jaguar_resty: ^2.5.8
  http:
  client_cookie: