name: jaguar_common
description: Jaguar stuff common to both server and client. Uses neither dart:io nor dart:html
version: 3.0.0
homepage: https://jaguar-dart.github.io/

documentation:

environment:
  sdk: ">=2.12.0 <3.0.0"

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.2.0
