name: jaguar_common
description: Jaguar stuff common to both server and client. Uses neither dart:io nor dart:html
version: 2.1.4
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://jaguar-dart.github.io/

documentation:

environment:
  sdk: ">=2.0.0 <3.0.0"

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.2.0
