name: jaguar_cors
description: CORS interceptor for Jaguar
version: 2.0.1
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/jaguar-dart/jaguar/cors
documentation:

environment:
  sdk: ">=1.23.0 <2.0.0"

dependencies:
  jaguar: ^2.0.2

dev_dependencies:
  test:
  jaguar_resty: ^2.2.2
  http:
