name: jaguar_cors
description: CORS interceptor for Jaguar. Use Cors interceptor and CorsOptions configuration class to add CORS support to Jaguar server applications.
version: 2.4.4
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: http://jaguar-dart.github.io
documentation:

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  jaguar: ^2.4.4

dev_dependencies:
  test:
  jaguar_resty: ^2.8.0
  http:
