name: jaguar_cors
description: CORS interceptor for Jaguar. Use Cors interceptor and CorsOptions configuration class to add CORS support to Jaguar server applications.
version: 3.0.1
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: http://jaguar-dart.github.io

documentation:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  jaguar: ^3.0.6

dev_dependencies:
  test:
  jaguar_resty: ^3.0.0
  http:
