name: jaguar_throttle
description: Rate limiter for Jaguar
version: 2.1.4
homepage: https://github.com/Jaguar-dart/jaguar_throttle
author: Ravi Teja Gudapati <tejainece@gmail.com>
documentation:

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  jaguar: ^2.1.37
  jaguar_cache: ^2.1.2

dev_dependencies:
  test: ^1.3.0
  jaguar_client: ^2.2.1
