name: jaguar_oauth
description: OAuth interceptors for Jaguar
version: 2.1.1
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: https://github.com/Jaguar-dart/jaguar_oauth
documentation:

environment:
  sdk: ">=1.24.0 <2.0.0"

dependencies:
  jaguar: ^2.1.1
  oauth2: ^1.2.0

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
  jaguar_facebook_client: '>=0.0.4 <0.1.0'
  jaguar_reflect:
  jaguar_settings: