name: path_tree
description: A fast data structure to match HTTP URL routes. Also handles regular expression (regexp) and glob path segments.
version: 3.0.0
homepage: http://jaguar-dart.github.io

documentation:

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.16.0
