name: jaguar_reflect
description: Reflection based alternative for Jaguar
version: 2.1.2
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: http://jaguar-dart.github.io

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  jaguar: ^2.1.6
dev_dependencies:
  jaguar_resty: ^2.2.2
  test: ^0.12.15+10
  http: