name: jaguar_reflect
description: Reflection based alternative for Jaguar
version: 2.1.5
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: http://jaguar-dart.github.io

environment:
  sdk: ">=2.0.0-dev.60.0 <3.0.0"

dependencies:
  jaguar: ^2.1.12

dev_dependencies:
  jaguar_resty: ^2.5.9
  test: ^1.2.0
  http: