name: jaguar_reflect
description: Logic to reflect Jaguar Controllers into Jaguar routes. Also provides reflection support for Jaguar Bingings
version: 2.4.2
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: http://jaguar-dart.github.io

environment:
  sdk: ">=2.0.0-dev.65 <3.0.0"

dependencies:
  jaguar: ^2.4.21
  meta: '>1.1.0 <2.0.0'

dev_dependencies:
  jaguar_resty: ^2.8.0
  test: ^1.3.0
  http: