name: jaguar_reflect
description: Reflection based alternative for Jaguar
version: 2.1.4
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: http://jaguar-dart.github.io

environment:
  sdk: ">=2.0.0-dev.65.0 <3.0.0"

dependencies:
  jaguar: ^2.1.9

dev_dependencies:
  jaguar_resty: ^2.5.9
  test: ^1.2.0
  http:

dependency_overrides:
  jaguar:
    path: ../jaguar