name: jaguar_reflect
description: Reflection based alternative for Jaguar
version: 2.4.1
authors:
- Ravi Teja Gudapati <tejainece@gmail.com>
- Kevin Segaud <segaud.kevin@gmail.com>
homepage: http://jaguar-dart.github.io

environment:
  sdk: ">=2.0.0-dev.65 <3.0.0"

dependencies:
  jaguar: ^2.4.1

dev_dependencies:
  jaguar_resty: ^2.8.0
  test: ^1.3.0
  http:

dependency_overrides:
  jaguar:
    path: ../jaguar